# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chatbot.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rchatbot.proto\x12\x07\x63hatbot\"!\n\x0e\x43hatBotRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\"#\n\x0f\x43hatBotResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\x8d\x01\n\x0e\x43hatbotService\x12\x38\n\x08SayHello\x12\x15.chatbot.HelloRequest\x1a\x13.chatbot.HelloReply\"\x00\x12\x41\n\nGetBotData\x12\x17.chatbot.ChatBotRequest\x1a\x18.chatbot.ChatBotResponse\"\x00\x42/Z-github.com/avinashsinghavin/Chatbot/grpcProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatbot_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z-github.com/avinashsinghavin/Chatbot/grpcProto'
  _globals['_CHATBOTREQUEST']._serialized_start=26
  _globals['_CHATBOTREQUEST']._serialized_end=59
  _globals['_CHATBOTRESPONSE']._serialized_start=61
  _globals['_CHATBOTRESPONSE']._serialized_end=96
  _globals['_HELLOREQUEST']._serialized_start=98
  _globals['_HELLOREQUEST']._serialized_end=126
  _globals['_HELLOREPLY']._serialized_start=128
  _globals['_HELLOREPLY']._serialized_end=157
  _globals['_CHATBOTSERVICE']._serialized_start=160
  _globals['_CHATBOTSERVICE']._serialized_end=301
# @@protoc_insertion_point(module_scope)
