# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcChatbot.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11grpcChatbot.proto\x12\x04grpc\"!\n\x0eMessageRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\"#\n\x0fMessageResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"\x1c\n\x0cImageRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x1c\n\x0eImageIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\")\n\rImageResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x32\xbc\x01\n\x0cImageService\x12\x36\n\tSaveImage\x12\x12.grpc.ImageRequest\x1a\x13.grpc.ImageResponse\"\x00\x12\x37\n\x08GetImage\x12\x14.grpc.ImageIdRequest\x1a\x13.grpc.ImageResponse\"\x00\x12;\n\nGetMessage\x12\x14.grpc.MessageRequest\x1a\x15.grpc.MessageResponse\"\x00\x42*Z(github.com/avinashsinghavin/chatbot/grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpcChatbot_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(github.com/avinashsinghavin/chatbot/grpc'
  _globals['_MESSAGEREQUEST']._serialized_start=27
  _globals['_MESSAGEREQUEST']._serialized_end=60
  _globals['_MESSAGERESPONSE']._serialized_start=62
  _globals['_MESSAGERESPONSE']._serialized_end=97
  _globals['_IMAGEREQUEST']._serialized_start=99
  _globals['_IMAGEREQUEST']._serialized_end=127
  _globals['_IMAGEIDREQUEST']._serialized_start=129
  _globals['_IMAGEIDREQUEST']._serialized_end=157
  _globals['_IMAGERESPONSE']._serialized_start=159
  _globals['_IMAGERESPONSE']._serialized_end=200
  _globals['_IMAGESERVICE']._serialized_start=203
  _globals['_IMAGESERVICE']._serialized_end=391
# @@protoc_insertion_point(module_scope)
