# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpcChatbot_pb2 as grpcChatbot__pb2


class ImageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveImage = channel.unary_unary(
                '/grpc.ImageService/SaveImage',
                request_serializer=grpcChatbot__pb2.ImageRequest.SerializeToString,
                response_deserializer=grpcChatbot__pb2.ImageResponse.FromString,
                )
        self.GetImage = channel.unary_unary(
                '/grpc.ImageService/GetImage',
                request_serializer=grpcChatbot__pb2.ImageIdRequest.SerializeToString,
                response_deserializer=grpcChatbot__pb2.ImageResponse.FromString,
                )
        self.GetMessage = channel.unary_unary(
                '/grpc.ImageService/GetMessage',
                request_serializer=grpcChatbot__pb2.MessageRequest.SerializeToString,
                response_deserializer=grpcChatbot__pb2.MessageResponse.FromString,
                )


class ImageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SaveImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveImage': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveImage,
                    request_deserializer=grpcChatbot__pb2.ImageRequest.FromString,
                    response_serializer=grpcChatbot__pb2.ImageResponse.SerializeToString,
            ),
            'GetImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetImage,
                    request_deserializer=grpcChatbot__pb2.ImageIdRequest.FromString,
                    response_serializer=grpcChatbot__pb2.ImageResponse.SerializeToString,
            ),
            'GetMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessage,
                    request_deserializer=grpcChatbot__pb2.MessageRequest.FromString,
                    response_serializer=grpcChatbot__pb2.MessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.ImageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SaveImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.ImageService/SaveImage',
            grpcChatbot__pb2.ImageRequest.SerializeToString,
            grpcChatbot__pb2.ImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.ImageService/GetImage',
            grpcChatbot__pb2.ImageIdRequest.SerializeToString,
            grpcChatbot__pb2.ImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.ImageService/GetMessage',
            grpcChatbot__pb2.MessageRequest.SerializeToString,
            grpcChatbot__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
